### ISSUE TITLE
Ready Prompt

### ISSUE THREAD

**Issue by OzHawk** [paulscottrobson/eris#27]
This may seem like an unlikely request.  But is it posible to have a "Ready" prompt?

I have a feeling that you have modelled this basic around the ZX Spectrum, however, coming from an TRS-80, Atari and Commodore background, I find it confusing not having a prompt to tell me that the computer has finished doing the last thing that I asked it to do and is waiting for me to ask it the next thing.

**Comment by paulscottrobson** [comment]
It's actually modelled on the Commodore system (I had a PET2001). The reason for the Spectrum style "screen at a time" is the poor scrolling. This is because I didn't want to simply throw hardware at the problem so the blitter does all the work and it is actually electronically pretty simple. The blitter can scroll quite fast (e.g. Frogger) but all the lookups and character drawing makes it slow. The problem with printing "READY" is it would stuff up the edited line it is printed on, though it could be perhaps done on execution of a command rather than editing. I'll think about this one.

**Comment by paulscottrobson** [comment]
Added Ready. Does not show on List, any error, or if editing a line. Seems to work okay.
